services:
  - type: web
    name: analog-search
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
      - key: GIGACHAT_AUTH_KEY
        sync: false
      - key: GIGACHAT_SCOPE
        value: GIGACHAT_API_PERS
      - key: GIGACHAT_MODEL
        value: GigaChat
